services:
  smartwebscraper.api:
    image: ${DOCKER_REGISTRY-}smartwebscraperapi
    build:
      context: .
      dockerfile: SmartWebScraper.API/Dockerfile
    depends_on:
      - smartwebscraper.db
    env_file: .env
    environment:
      - ConnectionStrings__DefaultConnection=$ConnectionString
    restart: unless-stopped

  smartwebscraper.db:
    image: mcr.microsoft.com/mssql/server
    container_name: webscraperdb
    hostname: smartwebscraper.db
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
      - MSSQL_DB_NAME=SmartWebScrapperDb
    ports:
      - 1401:1433

  smartwebscraper.client:
    image: "node:20-alpine"
    working_dir: /app
    command: sh -c "npm ci && npm start -- --host 0.0.0.0 --disable-host-check"
    ports:
      - 4200:4200
    volumes:
      - ./SmartWebScraper.Client:/app
    environment:
      - NODE_ENV=development
