services:
  smartwebscraper.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
    ports:
      - "8080:8080"
